### ISSUE TITLE
Takový nápad

### ISSUE THREAD

**Issue by paveljanecek** [LaskaKit/ESP32-C3-LPKit#1]
Dobrý den,

v další iteraci desky, by (alespoň mě) přišlo vhod, změnit jumper ADC_IO0 na dvoucestný, aby se dalo snadno na přímo propojit IO0 s A0. Takhle jsem musel odpájet R7 a C7 a pak R6 nahradit 0R rezistorem a propojit oba jumpery.

Díky

![image](https://github.com/LaskaKit/ESP32-C3-LPKit/assets/40796695/68487cd6-74c7-47b3-ba1b-d97ee2bf25a8)

**Comment by Konstantin-G** [comment]
Zdravím, přidáme.
