### ISSUE TITLE
I2C pin warning (pins 1,2 don't work, only pins 8,10 do)

### ISSUE THREAD

**Issue by 3top1a** [LaskaKit/ESP32-C3-LPKit#2]
Hi,

I've just spent 5 days debugging an I2C issue, just to find out that you can't use I2C on pins 1 and 2.
Maybe rewrite the warning to say "not only do you need to use Wire.begin(8, 10) but also you need to use pins 8 and 10 otherwise I2C won't work"?

Thanks.

**Comment by Konstantin-G** [comment]
Hi, we have not checked if there pins working for I2C or not. We have dedicated pins 8 and 10 for I2C with connector.
What did you try to connect to I2C? Does it have pull-ups? because IO2 already have 10k pull-up...

**Comment by 3top1a** [comment]
I have tried, and it did show up on a I2C scanner, but no data got through. It's possible the ESP C3 chip reserves those pins.

**Comment by Konstantin-G** [comment]
you did not answer. What did you try to connect to I2C? Does it have pull-ups?

**Comment by 3top1a** [comment]
Ah, sorry. I was connecting a BNO085 IMU. [I tried connecting a 2K resistor to SDA but nothing.](https://forums.adafruit.com/viewtopic.php?p=1001700#p1001700)

**Comment by Konstantin-G** [comment]
ohh, I think it is something with Adafruit level shifter and I2C pull-ups on sensor.
